### ISSUE TITLE
Use Cases User Profile

### ISSUE THREAD

**Issue by cmbuhler** [CMPUT301W18T14/PraiseTheSun#2]

**Comment by tlafranc** [comment]
Hey Chase in the notes when there was a repeat of steps in the exception, instead of repeating the steps the professor wrote "System returns to step 1" (slide #37). 
For example, for you exception for "Authenticate" you wrote "System notifies user that the entered credentials are invalid and prompts user for re-entry of username and password". Perhaps you can make that two points "1) System notifies user that the entered credentials are invalid" and then "2) System returns to step 1"
